"""Smoke-scale baseline and ablation utilities."""

from .governor_ablation import (
    GovernorAblationComparison,
    UnfilteredCandidateScore,
    UnfilteredPrimitiveSelector,
    UnfilteredPrimitiveSelectorConfig,
    UnfilteredSelectionDecision,
    compare_governor_to_unfiltered,
)
from .reference_tracking import (
    ReferenceTrackingConfig,
    ReferenceTrackingController,
    ReferenceTrackingRolloutRecord,
    build_gate_tracking_target,
    run_reference_tracking_rollout,
)
from .registry import (
    B0_OPEN_LOOP_DIAGNOSTIC,
    B1_UNGOVERNED_PRIMITIVE_SELECTOR,
    B2_FILTER_ONLY_NO_DEGRADATION,
    B3_NO_RETURNABILITY_SELECTOR,
    B4_TRAJECTORY_TRACKING_LQR_TVLQR,
    B5_ENERGY_LATERAL_GUIDANCE,
    B6_WIND_AWARE_GUIDANCE,
    B7_INNER_LOOP_SUBSTITUTION,
    B8_LIFT_EVIDENCE_REMOVED,
    BASELINE_ALIASES,
    BASELINE_COMMON_SCHEMA_FIELDS,
    BASELINE_METHOD_NAMES,
    BASELINE_REGISTRY,
    BaselineScaffold,
    BaselineSmokeRecord,
    BaselineSpec,
    baseline_registry_records,
    baseline_spec,
    instantiate_baseline,
)

__all__ = [
    "GovernorAblationComparison",
    "B0_OPEN_LOOP_DIAGNOSTIC",
    "B1_UNGOVERNED_PRIMITIVE_SELECTOR",
    "B2_FILTER_ONLY_NO_DEGRADATION",
    "B3_NO_RETURNABILITY_SELECTOR",
    "B4_TRAJECTORY_TRACKING_LQR_TVLQR",
    "B5_ENERGY_LATERAL_GUIDANCE",
    "B6_WIND_AWARE_GUIDANCE",
    "B7_INNER_LOOP_SUBSTITUTION",
    "B8_LIFT_EVIDENCE_REMOVED",
    "BASELINE_ALIASES",
    "BASELINE_COMMON_SCHEMA_FIELDS",
    "BASELINE_METHOD_NAMES",
    "BASELINE_REGISTRY",
    "BaselineScaffold",
    "BaselineSmokeRecord",
    "BaselineSpec",
    "ReferenceTrackingConfig",
    "ReferenceTrackingController",
    "ReferenceTrackingRolloutRecord",
    "UnfilteredCandidateScore",
    "UnfilteredPrimitiveSelector",
    "UnfilteredPrimitiveSelectorConfig",
    "UnfilteredSelectionDecision",
    "baseline_registry_records",
    "baseline_spec",
    "build_gate_tracking_target",
    "compare_governor_to_unfiltered",
    "instantiate_baseline",
    "run_reference_tracking_rollout",
]
